// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: chat/letter_box.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type LetterBox struct {
	Count    uint64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Messages string `protobuf:"bytes,2,opt,name=messages,proto3" json:"messages,omitempty"`
}

func (m *LetterBox) Reset()         { *m = LetterBox{} }
func (m *LetterBox) String() string { return proto.CompactTextString(m) }
func (*LetterBox) ProtoMessage()    {}
func (*LetterBox) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d43ee39654f1fd4, []int{0}
}
func (m *LetterBox) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LetterBox) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LetterBox.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LetterBox) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LetterBox.Merge(m, src)
}
func (m *LetterBox) XXX_Size() int {
	return m.Size()
}
func (m *LetterBox) XXX_DiscardUnknown() {
	xxx_messageInfo_LetterBox.DiscardUnknown(m)
}

var xxx_messageInfo_LetterBox proto.InternalMessageInfo

func (m *LetterBox) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *LetterBox) GetMessages() string {
	if m != nil {
		return m.Messages
	}
	return ""
}

func init() {
	proto.RegisterType((*LetterBox)(nil), "chat.chat.LetterBox")
}

func init() { proto.RegisterFile("chat/letter_box.proto", fileDescriptor_7d43ee39654f1fd4) }

var fileDescriptor_7d43ee39654f1fd4 = []byte{
	// 147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0xce, 0x48, 0x2c,
	0xd1, 0xcf, 0x49, 0x2d, 0x29, 0x49, 0x2d, 0x8a, 0x4f, 0xca, 0xaf, 0xd0, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0xe2, 0x04, 0x09, 0xeb, 0x81, 0x08, 0x25, 0x5b, 0x2e, 0x4e, 0x1f, 0xb0, 0xb4, 0x53,
	0x7e, 0x85, 0x90, 0x08, 0x17, 0x6b, 0x72, 0x7e, 0x69, 0x5e, 0x89, 0x04, 0xa3, 0x02, 0xa3, 0x06,
	0x4b, 0x10, 0x84, 0x23, 0x24, 0xc5, 0xc5, 0x91, 0x9b, 0x5a, 0x5c, 0x9c, 0x98, 0x9e, 0x5a, 0x2c,
	0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe7, 0x3b, 0x69, 0x9f, 0x78, 0x24, 0xc7, 0x78, 0xe1,
	0x91, 0x1c, 0xe3, 0x83, 0x47, 0x72, 0x8c, 0x13, 0x1e, 0xcb, 0x31, 0x5c, 0x78, 0x2c, 0xc7, 0x70,
	0xe3, 0xb1, 0x1c, 0x43, 0x94, 0x20, 0xd8, 0xea, 0x0a, 0x7d, 0x30, 0x55, 0x52, 0x59, 0x90, 0x5a,
	0x9c, 0xc4, 0x06, 0xb6, 0xdd, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x0d, 0x34, 0x89, 0x6b, 0x96,
	0x00, 0x00, 0x00,
}

func (m *LetterBox) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LetterBox) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LetterBox) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Messages) > 0 {
		i -= len(m.Messages)
		copy(dAtA[i:], m.Messages)
		i = encodeVarintLetterBox(dAtA, i, uint64(len(m.Messages)))
		i--
		dAtA[i] = 0x12
	}
	if m.Count != 0 {
		i = encodeVarintLetterBox(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintLetterBox(dAtA []byte, offset int, v uint64) int {
	offset -= sovLetterBox(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *LetterBox) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Count != 0 {
		n += 1 + sovLetterBox(uint64(m.Count))
	}
	l = len(m.Messages)
	if l > 0 {
		n += 1 + l + sovLetterBox(uint64(l))
	}
	return n
}

func sovLetterBox(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLetterBox(x uint64) (n int) {
	return sovLetterBox(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *LetterBox) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLetterBox
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LetterBox: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LetterBox: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLetterBox
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Messages", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLetterBox
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLetterBox
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLetterBox
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Messages = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLetterBox(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLetterBox
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLetterBox(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLetterBox
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLetterBox
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLetterBox
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLetterBox
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLetterBox
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLetterBox
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLetterBox        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLetterBox          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLetterBox = fmt.Errorf("proto: unexpected end of group")
)
